// <auto-generated />
using MessageBoard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MessageBoard.Migrations
{
    [DbContext(typeof(MessageBoardContext))]
    [Migration("20200330180543_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MessageBoard.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Group");

                    b.Property<string>("UserName");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 3,
                            Content = "where the tp",
                            Group = "Shopping Boi's",
                            UserName = "Female"
                        },
                        new
                        {
                            MessageId = 4,
                            Content = "Pip",
                            Group = "Shark",
                            UserName = "leggo"
                        },
                        new
                        {
                            MessageId = 5,
                            Content = "Bartholomew's fancy hats",
                            Group = "Boi's and their hats",
                            UserName = "noodle_boi_hat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
