// <auto-generated />
using System;
using MessageBoard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MessageBoard.Migrations
{
    [DbContext(typeof(MessageBoardContext))]
    [Migration("20200330230336_Resart")]
    partial class Resart
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MessageBoard.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<DateTime>("PostDate");

                    b.Property<string>("UserName");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            Content = "where the tp",
                            Group = "Shopping Boi's",
                            PostDate = new DateTime(2015, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "Female"
                        },
                        new
                        {
                            MessageId = 2,
                            Content = "Pip",
                            Group = "Shark",
                            PostDate = new DateTime(2020, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "leggo"
                        },
                        new
                        {
                            MessageId = 3,
                            Content = "Bartholomew's fancy hats",
                            Group = "Shark",
                            PostDate = new DateTime(2017, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "noodle_boi_hat"
                        },
                        new
                        {
                            MessageId = 4,
                            Content = "Pip",
                            Group = "Shopping Boi's",
                            PostDate = new DateTime(2019, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "noodle_boi_hat"
                        },
                        new
                        {
                            MessageId = 5,
                            Content = "doppledonger",
                            Group = "Firework Sales",
                            PostDate = new DateTime(2017, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "Female"
                        },
                        new
                        {
                            MessageId = 6,
                            Content = "bart",
                            Group = "Shark",
                            PostDate = new DateTime(2015, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "Female"
                        },
                        new
                        {
                            MessageId = 7,
                            Content = "bart",
                            Group = "Firework Sales",
                            PostDate = new DateTime(2019, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "leggo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
